services:
    app.repository.article:
        class: AppBundle\Entity\Repository\ArticleRepository
        factory: [ @doctrine.orm.default_entity_manager, getRepository ]
        arguments:
            - AppBundle\Entity\Article